// This file is for reference only - it shows the database schema

/*
Table: students
- id: uuid (primary key, generated by Supabase)
- name: text (student's name)
- student_id: text (unique student ID)
- password: text (student's password)
- created_at: timestamp with time zone (default: now())

Table: test_scores
- id: uuid (primary key, generated by Supabase)
- student_id: text (references students.student_id)
- test_name: text (name of the test)
- test_date: date (date when the test was taken)
- score: integer (student's score)
- max_score: integer (maximum possible score)
- created_at: timestamp with time zone (default: now())
*/

// SQL to create these tables:

/*
-- Create students table
CREATE TABLE students (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  student_id TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create test_scores table
CREATE TABLE test_scores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id TEXT NOT NULL REFERENCES students(student_id),
  test_name TEXT NOT NULL,
  test_date DATE NOT NULL,
  score INTEGER NOT NULL,
  max_score INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX idx_test_scores_student_id ON test_scores(student_id);
*/
